[mangaright]
spec.version = "1.1.0"
api.version = "1.1.0"

[plugin]
id = "52b3a063-ce43-4c21-ae37-4b7cae945306"

[plugin.name]
primary = "mangakatana"
aliases = ["mangakatana"]

[plugin.general]
version = "1.0.0"
author = "rcribbs"
